### PR TITLE
Some fixes for dragonflight expension

### PR DESCRIPTION
**Pull request by nulian**
Hey had to make some changes to make it work in dragonflight.
Not done any wow lua stuff yet before so it's a bit messy.

Thought maybe you can use some of the changes to make the addon fully compatible in the future.

Issues found on beta

- Commented and removed some lines in Frame.xml of invalid fields according to wow.
- Disabled setLight because it gave some error about boolean not being able to iterate upon but couldn't find what changed that broke it.
- Disabled closeGossip calls don't seem to change working and it caused c errors
- Changed select gossip /active quest calls to get questID or gossipOptionID
- Disabled some gradiant stuff because that api has been removed and I didn't know how to do it otherwise

### CODE REVIEW

**Comment by seblindfors** [comment]
Here's how SetLight works now:
```lua
local lightValues = {
   omnidirectional = false,
   point = CreateVector3D(0, 0, 0),
   ambientIntensity = .7,
   ambientColor = CreateColor(1, 1, 1),
   diffuseIntensity = 0,
   diffuseColor = CreateColor(1, 1, 1)
};
local enabled = true;
self:SetLight(enabled, lightValues);
```

As for SetGradientAlpha, it's now SetGradient, with this signature:
```lua
local orientation, minR, minG, minB, minA, maxR, maxG, maxB, maxA = ... -- old
local minR, minG, minB, minA = CreateColor(...):GetRGBA()
local maxR, maxG, maxB, maxA = CreateColor(select(5, ...)):GetRGBA()
return texture:SetGradientAlpha(orientation, minR, minG, minB, minA, maxR, maxG, maxB, maxA)
```

**Comment by nulian** [comment]
The SetLight was about this part not sure how that can be fixed.

```
local model = talkbox.MainFrame.Model
model:SetLight(unpack(L.ModelMixin.LightValues))

L.Mixin(model, L.ModelMixin)
```

**Comment by nulian** [comment]
I did fix all the grandient alpha's.

It seems blizzard also broke the fallback for SelectGossipOption so I had to disable that line.
The function seems to be found now but does nothing.
`--if SelectGossipOption then return SelectGossipOption(...) end`

**Comment by nulian** [comment]
Tried to fix auto closing on things like flight master and the auto select of gossip skipping too much.

**Pull request closed without merging**
