### PR TITLE
Add combat lockdown conditional check for SetPropagateKeyboardInput(), fixes issue #32

### PR DESCRIPTION
**Pull request by brittyazel**
[In 10.1.5](https://warcraft.wiki.gg/wiki/Patch_10.1.5/API_changes) Blizzard made [frame:SetPropagateKeyboardInput()](https://warcraft.wiki.gg/wiki/API_Frame_SetPropagateKeyboardInput) a restricted function that is no longer able to be called in combat from insecure code. To work around this limitation, this patch wraps the calls to this function with an InCombatLockdown() conditional check.

This patch fixes issue #32, and from my testing does not break anything that I have noticed.

### CODE REVIEW

**Comment by brittyazel** [comment]
Please let me know if you'd like me to add any refinements to this patch.

**Comment by brittyazel** [comment]
Just following up again on this one. If you need any help maintaining this project, I'd be more than happy to help out. With 10.2.5 coming in just a little over a week, it'd be great to have this 10.1.5 bug finally fixed.

**Comment by brittyazel** [comment]
@seblindfors Apologies for pinging you (again), but I just saw that you released a new version validating Immersion for 10.2.5, but #32 continues to be an issue since 10.1.5, and my patch does resolve it without any noticeable issues. Any chance you can pull this patch in, or at least give it a review?

**Comment by brittyazel** [comment]
@seblindfors Hey, I hate to be the guy pestering about this, but do you think you can review this and get it merged? The taint errors pop up constantly

**Comment by seblindfors** [comment]
Sorry, I don't pay much attention to Immersion. This looks good :)

**Comment by seblindfors** [comment]
I actually did some work to handle this issue by adding a secure handler to fish for NPC exists state, so we can still use key bindings in combat, but never finished it. Like I said, Immersion is not a very interesting project to me at this point. Here's the code anyway (uncompleted):

[securestuff.patch](https://github.com/seblindfors/Immersion/files/15253666/securestuff.patch)

**Comment by brittyazel** [comment]
Thanks for the merge! I'm happy to help maintain the project if you're not wanting to spend much time on it. Just lemme know :-)

**Comment by seblindfors** [comment]
Thank you, that help is welcome. I don't want to neglect it, but I'm trying to work on other things and Immersion has suffered because of that.

**Comment by brittyazel** [comment]
Awesome! Just let me know in what form you'd like my help to take. I can help co-maintain, or just send occasional PRs. You don't really 'know' me, so it's understandable for you to not to want to hand over any keys until some trust is built lol.

I'm the author of [Enhanced Raid Frames](https://github.com/brittyazel/EnhancedRaidFrames) and [DevTool](https://github.com/brittyazel/DevTool) (among a few other side projects). Feel free to take a look at my code if you want to get a sense of my style

**Pull request merged**
